//go:build !nesgo
// +build !nesgo

package cpu

import (
	. "github.com/retroenv/nesgo/pkg/addressing"
)

// Opcode is a NES CPU opcode that contains the instruction info and used
// addressing mode.
type Opcode struct {
	Instruction *Instruction
	Addressing  Mode
}

// Opcodes maps first opcode bytes to NES CPU instruction information.
var Opcodes = map[byte]Opcode{
	0x00: {Instruction: brk, Addressing: ImpliedAddressing},
	0x01: {Instruction: ora, Addressing: IndirectXAddressing},
	0x05: {Instruction: ora, Addressing: ZeroPageAddressing},
	0x06: {Instruction: asl, Addressing: ZeroPageAddressing},
	0x08: {Instruction: php, Addressing: ImpliedAddressing},
	0x09: {Instruction: ora, Addressing: ImmediateAddressing},
	0x0a: {Instruction: asl, Addressing: AccumulatorAddressing},
	0x0d: {Instruction: ora, Addressing: AbsoluteAddressing},
	0x0e: {Instruction: asl, Addressing: AbsoluteAddressing},
	0x10: {Instruction: bpl, Addressing: RelativeAddressing},
	0x11: {Instruction: ora, Addressing: IndirectYAddressing},
	0x15: {Instruction: ora, Addressing: ZeroPageXAddressing},
	0x16: {Instruction: asl, Addressing: ZeroPageXAddressing},
	0x18: {Instruction: clc, Addressing: ImpliedAddressing},
	0x19: {Instruction: ora, Addressing: AbsoluteYAddressing},
	0x1d: {Instruction: ora, Addressing: AbsoluteXAddressing},
	0x1e: {Instruction: asl, Addressing: AbsoluteXAddressing},
	0x20: {Instruction: jsr, Addressing: AbsoluteAddressing},
	0x21: {Instruction: and, Addressing: IndirectXAddressing},
	0x24: {Instruction: bit, Addressing: ZeroPageAddressing},
	0x25: {Instruction: and, Addressing: ZeroPageAddressing},
	0x26: {Instruction: rol, Addressing: ZeroPageAddressing},
	0x28: {Instruction: plp, Addressing: ImpliedAddressing},
	0x29: {Instruction: and, Addressing: ImmediateAddressing},
	0x2a: {Instruction: rol, Addressing: AccumulatorAddressing},
	0x2c: {Instruction: bit, Addressing: AbsoluteAddressing},
	0x2d: {Instruction: and, Addressing: AbsoluteAddressing},
	0x2e: {Instruction: rol, Addressing: AbsoluteAddressing},
	0x30: {Instruction: bmi, Addressing: RelativeAddressing},
	0x31: {Instruction: and, Addressing: IndirectYAddressing},
	0x35: {Instruction: and, Addressing: ZeroPageXAddressing},
	0x36: {Instruction: rol, Addressing: ZeroPageXAddressing},
	0x38: {Instruction: sec, Addressing: ImpliedAddressing},
	0x39: {Instruction: and, Addressing: AbsoluteYAddressing},
	0x3d: {Instruction: and, Addressing: AbsoluteXAddressing},
	0x3e: {Instruction: rol, Addressing: AbsoluteXAddressing},
	0x40: {Instruction: rti, Addressing: ImpliedAddressing},
	0x41: {Instruction: eor, Addressing: IndirectXAddressing},
	0x45: {Instruction: eor, Addressing: ZeroPageAddressing},
	0x46: {Instruction: lsr, Addressing: ZeroPageAddressing},
	0x48: {Instruction: pha, Addressing: ImpliedAddressing},
	0x49: {Instruction: eor, Addressing: ImmediateAddressing},
	0x4a: {Instruction: lsr, Addressing: AccumulatorAddressing},
	0x4c: {Instruction: jmp, Addressing: AbsoluteAddressing},
	0x4d: {Instruction: eor, Addressing: AbsoluteAddressing},
	0x4e: {Instruction: lsr, Addressing: AbsoluteAddressing},
	0x50: {Instruction: bvc, Addressing: RelativeAddressing},
	0x51: {Instruction: eor, Addressing: IndirectYAddressing},
	0x55: {Instruction: eor, Addressing: ZeroPageXAddressing},
	0x56: {Instruction: lsr, Addressing: ZeroPageXAddressing},
	0x58: {Instruction: cli, Addressing: ImpliedAddressing},
	0x59: {Instruction: eor, Addressing: AbsoluteYAddressing},
	0x5d: {Instruction: eor, Addressing: AbsoluteXAddressing},
	0x5e: {Instruction: lsr, Addressing: AbsoluteXAddressing},
	0x60: {Instruction: rts, Addressing: ImpliedAddressing},
	0x61: {Instruction: adc, Addressing: IndirectXAddressing},
	0x65: {Instruction: adc, Addressing: ZeroPageAddressing},
	0x66: {Instruction: ror, Addressing: ZeroPageAddressing},
	0x68: {Instruction: pla, Addressing: ImpliedAddressing},
	0x69: {Instruction: adc, Addressing: ImmediateAddressing},
	0x6a: {Instruction: ror, Addressing: AccumulatorAddressing},
	0x6c: {Instruction: jmp, Addressing: IndirectAddressing},
	0x6d: {Instruction: adc, Addressing: AbsoluteAddressing},
	0x6e: {Instruction: ror, Addressing: AbsoluteAddressing},
	0x70: {Instruction: bvs, Addressing: RelativeAddressing},
	0x71: {Instruction: adc, Addressing: IndirectYAddressing},
	0x75: {Instruction: adc, Addressing: ZeroPageXAddressing},
	0x76: {Instruction: ror, Addressing: ZeroPageXAddressing},
	0x78: {Instruction: sei, Addressing: ImpliedAddressing},
	0x79: {Instruction: adc, Addressing: AbsoluteYAddressing},
	0x7d: {Instruction: adc, Addressing: AbsoluteXAddressing},
	0x7e: {Instruction: ror, Addressing: AbsoluteXAddressing},
	0x81: {Instruction: sta, Addressing: IndirectXAddressing},
	0x84: {Instruction: sty, Addressing: ZeroPageAddressing},
	0x85: {Instruction: sta, Addressing: ZeroPageAddressing},
	0x86: {Instruction: stx, Addressing: ZeroPageAddressing},
	0x88: {Instruction: dey, Addressing: ImpliedAddressing},
	0x8a: {Instruction: txa, Addressing: ImpliedAddressing},
	0x8c: {Instruction: sty, Addressing: AbsoluteAddressing},
	0x8d: {Instruction: sta, Addressing: AbsoluteAddressing},
	0x8e: {Instruction: stx, Addressing: AbsoluteAddressing},
	0x90: {Instruction: bcc, Addressing: RelativeAddressing},
	0x91: {Instruction: sta, Addressing: IndirectYAddressing},
	0x94: {Instruction: sty, Addressing: ZeroPageXAddressing},
	0x95: {Instruction: sta, Addressing: ZeroPageXAddressing},
	0x96: {Instruction: stx, Addressing: ZeroPageYAddressing},
	0x98: {Instruction: tya, Addressing: ImpliedAddressing},
	0x99: {Instruction: sta, Addressing: AbsoluteYAddressing},
	0x9a: {Instruction: txs, Addressing: ImpliedAddressing},
	0x9d: {Instruction: sta, Addressing: AbsoluteXAddressing},
	0xa0: {Instruction: ldy, Addressing: ImmediateAddressing},
	0xa1: {Instruction: lda, Addressing: IndirectXAddressing},
	0xa2: {Instruction: ldx, Addressing: ImmediateAddressing},
	0xa4: {Instruction: ldy, Addressing: ZeroPageAddressing},
	0xa5: {Instruction: lda, Addressing: ZeroPageAddressing},
	0xa6: {Instruction: ldx, Addressing: ZeroPageAddressing},
	0xa8: {Instruction: tay, Addressing: ImpliedAddressing},
	0xa9: {Instruction: lda, Addressing: ImmediateAddressing},
	0xaa: {Instruction: tax, Addressing: ImpliedAddressing},
	0xac: {Instruction: ldy, Addressing: AbsoluteAddressing},
	0xad: {Instruction: lda, Addressing: AbsoluteAddressing},
	0xae: {Instruction: ldx, Addressing: AbsoluteAddressing},
	0xb0: {Instruction: bcs, Addressing: RelativeAddressing},
	0xb1: {Instruction: lda, Addressing: IndirectYAddressing},
	0xb4: {Instruction: ldy, Addressing: ZeroPageXAddressing},
	0xb5: {Instruction: lda, Addressing: ZeroPageXAddressing},
	0xb6: {Instruction: ldx, Addressing: ZeroPageYAddressing},
	0xb8: {Instruction: clv, Addressing: ImpliedAddressing},
	0xb9: {Instruction: lda, Addressing: AbsoluteYAddressing},
	0xba: {Instruction: tsx, Addressing: ImpliedAddressing},
	0xbc: {Instruction: ldy, Addressing: AbsoluteXAddressing},
	0xbd: {Instruction: lda, Addressing: AbsoluteXAddressing},
	0xbe: {Instruction: ldx, Addressing: AbsoluteYAddressing},
	0xc0: {Instruction: cpy, Addressing: ImmediateAddressing},
	0xc1: {Instruction: cmp, Addressing: IndirectXAddressing},
	0xc4: {Instruction: cpy, Addressing: ZeroPageAddressing},
	0xc5: {Instruction: cmp, Addressing: ZeroPageAddressing},
	0xc6: {Instruction: dec, Addressing: ZeroPageAddressing},
	0xc8: {Instruction: iny, Addressing: ImpliedAddressing},
	0xc9: {Instruction: cmp, Addressing: ImmediateAddressing},
	0xca: {Instruction: dex, Addressing: ImpliedAddressing},
	0xcc: {Instruction: cpy, Addressing: AbsoluteAddressing},
	0xcd: {Instruction: cmp, Addressing: AbsoluteAddressing},
	0xce: {Instruction: dec, Addressing: AbsoluteAddressing},
	0xd0: {Instruction: bne, Addressing: RelativeAddressing},
	0xd1: {Instruction: cmp, Addressing: IndirectYAddressing},
	0xd5: {Instruction: cmp, Addressing: ZeroPageXAddressing},
	0xd6: {Instruction: dec, Addressing: ZeroPageXAddressing},
	0xd8: {Instruction: cld, Addressing: ImpliedAddressing},
	0xd9: {Instruction: cmp, Addressing: AbsoluteYAddressing},
	0xdd: {Instruction: cmp, Addressing: AbsoluteXAddressing},
	0xde: {Instruction: dec, Addressing: AbsoluteXAddressing},
	0xe0: {Instruction: cpx, Addressing: ImmediateAddressing},
	0xe1: {Instruction: sbc, Addressing: IndirectXAddressing},
	0xe4: {Instruction: cpx, Addressing: ZeroPageAddressing},
	0xe5: {Instruction: sbc, Addressing: ZeroPageAddressing},
	0xe6: {Instruction: inc, Addressing: ZeroPageAddressing},
	0xe8: {Instruction: inx, Addressing: ImpliedAddressing},
	0xe9: {Instruction: sbc, Addressing: ImmediateAddressing},
	0xea: {Instruction: nop, Addressing: ImpliedAddressing},
	0xec: {Instruction: cpx, Addressing: AbsoluteAddressing},
	0xed: {Instruction: sbc, Addressing: AbsoluteAddressing},
	0xee: {Instruction: inc, Addressing: AbsoluteAddressing},
	0xf0: {Instruction: beq, Addressing: RelativeAddressing},
	0xf1: {Instruction: sbc, Addressing: IndirectYAddressing},
	0xf5: {Instruction: sbc, Addressing: ZeroPageXAddressing},
	0xf6: {Instruction: inc, Addressing: ZeroPageXAddressing},
	0xf8: {Instruction: sed, Addressing: ImpliedAddressing},
	0xf9: {Instruction: sbc, Addressing: AbsoluteYAddressing},
	0xfd: {Instruction: sbc, Addressing: AbsoluteXAddressing},
	0xfe: {Instruction: inc, Addressing: AbsoluteXAddressing},
}
