name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    timeout-minutes: 15

    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.16]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Install linter
        run: "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0"

      - name: Run linter
        run: golangci-lint linters && golangci-lint run

      - name: Test
        run: go test -tags nogui ./... -v
